typedef struct {
    AreaMap::vftable_69a52c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
    dword mbr_0x80;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    byte mbr_0x94;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
} AreaMap;
undefined __thiscall fwrite_file_from_mbrs(FILE * param_1);
undefined __thiscall meth_0x57ece0(void);
AreaMap * __thiscall ~AreaMap(void);
AreaMap * __thiscall AreaMap(undefined4 param_1, undefined4 param_2, _String_base * param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined4 param_9);
undefined4 * __thiscall virt_meth_0x57fcd0(byte param_1);
undefined __thiscall fread_file_into_mbrs(FILE * param_1);
typedef struct {
    virt_meth_0x57fcd0 * virt_meth_0x57fcd0_0;
    virt_meth_0x57ff40 * virt_meth_0x57ff40_4;
    virt_meth_0x57c140 * virt_meth_0x57c140_8;
} AreaMap::vftable_69a52c;
