typedef struct {
    AreaMapNote::vftable_69a520 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
} AreaMapNote;
undefined __thiscall meth_0x57c060(void);
AreaMapNote * __thiscall AreaMapNote(void);
AreaMapNote * __thiscall ~AreaMapNote(void);
undefined __thiscall meth_0x57d2e0(void);
int __thiscall meth_0x57d3a0(int param_1);
undefined __thiscall virt_meth_0x57d440(FILE * param_1);
AreaMapNote * __thiscall AreaMapNote(int param_1);
typedef struct {
    virt_meth_0x57d440 * virt_meth_0x57d440_0;
    virt_meth_0x57c8d0 * virt_meth_0x57c8d0_4;
} AreaMapNote::vftable_69a520;
