typedef struct {
    Audio::vftable_69e2ec * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x34;
    dword mbr_0x38;
    byte mbr_0x3c;
    byte mbr_0x3d;
    byte mbr_0x3e;
    undefined None;
    dword mbr_0x40;
    byte mbr_0x44;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
} Audio;
undefined __thiscall meth_0x5909e0(void);
Audio * __thiscall Audio(void);
undefined __thiscall virt_meth_0x590b50(void);
undefined __thiscall virt_meth_0x591110(void);
Audio * __thiscall ~Audio(void);
undefined4 * __thiscall virt_meth_0x5915b0(byte param_1);
typedef struct {
    virt_meth_0x5915b0 * virt_meth_0x5915b0_0;
    virt_meth_0x590be0 * virt_meth_0x590be0_4;
    virt_meth_0x590b50 * virt_meth_0x590b50_8;
    virt_meth_0x591110 * virt_meth_0x591110_12;
} Audio::vftable_69e2ec;
