#include "Gfx_CamCtrl_Orbit.h"
typedef struct {
    CameraControl::vftable_69bf28 * vftptr_0x0;
    dword mbr_0x4;
    Gfx_CamCtrl_Orbit Gfx_CamCtrl_Orbit;
    word mbr_0xc0;
    word mbr_0xc2;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xd4;
    dword mbr_0xd8;
    dword mbr_0xdc;
    dword mbr_0xe0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x100;
    dword mbr_0x104;
    dword mbr_0x108;
    dword mbr_0x10c;
    dword mbr_0x110;
    byte mbr_0x114;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x118;
    dword mbr_0x11c;
} CameraControl;
undefined __thiscall meth_0x585e20(undefined4 * param_1);
undefined __thiscall meth_0x585e60(float param_1);
undefined __thiscall meth_0x585fd0(float param_1);
undefined __thiscall meth_0x586110(float param_1);
undefined __thiscall meth_0x586330(void);
undefined __thiscall MoveTarget(undefined param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
CameraControl * __thiscall ~CameraControl(void);
undefined __thiscall meth_0x586590(char param_1);
undefined __thiscall meth_0x586710(undefined4 param_1, undefined4 param_2);
undefined __thiscall meth_0x586760(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined __thiscall meth_0x5867c0(float param_1);
undefined __thiscall meth_0x586830(void);
undefined __thiscall meth_0x5869c0(void);
CameraControl * __thiscall CameraControl(undefined4 param_1);
typedef struct {
    virt_meth_0x587030 * virt_meth_0x587030_0;
} CameraControl::vftable_69bf28;
