typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    byte mbr_0x50;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    byte mbr_0x74;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x78;
    dword mbr_0x7c;
    dword mbr_0x80;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xbc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0xc4;
    byte mbr_0xc5;
    byte mbr_0xc6;
    byte mbr_0xc7;
    byte mbr_0xc8;
    byte mbr_0xc9;
} cls_0x49cc40;
int __thiscall meth_0x49cc40(int param_1);
undefined __thiscall meth_0x49cc70(void);
undefined __thiscall meth_0x49cca0(uint param_1, char param_2, char param_3, uint * param_4);
undefined __thiscall meth_0x49cdd0(void);
undefined __thiscall meth_0x49ce10(undefined4 param_1);
undefined __thiscall meth_0x49ce40(undefined4 param_1);
undefined __thiscall meth_0x49ced0(undefined param_1);
undefined __thiscall meth_0x49cef0(undefined param_1);
undefined __thiscall meth_0x49cf10(undefined param_1);
undefined __thiscall meth_0x49cf30(float param_1, float param_2, float param_3);
undefined4 __thiscall meth_0x49db50(int param_1);
undefined __thiscall meth_0x49dd40(undefined4 param_1, undefined param_2);
undefined __thiscall meth_0x49e130(void);
undefined __thiscall meth_0x4a0750(float param_1);
undefined __thiscall meth_0x4a0dd0(int * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
