typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x20;
    dword mbr_0x24;
} cls_0x560a00;
undefined __thiscall meth_0x560a00(undefined4 * param_1, int * param_2);
undefined __thiscall meth_0x562c40(undefined4 * param_1, int * param_2);
