#include "CEngineInterface.h"
typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    byte mbr_0x5c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    byte mbr_0x78;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    byte mbr_0xac;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
    dword mbr_0xbc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    CEngineInterface CEngineInterface;
} cls_0x558740;
undefined __thiscall meth_0x434120(int param_1, int param_2);
undefined __thiscall meth_0x434250(void);
undefined __thiscall meth_0x4342c0(void);
undefined __thiscall meth_0x434760(void);
undefined __thiscall meth_0x434910(int param_1, int * param_2);
undefined __thiscall meth_0x557a50(void);
undefined __thiscall meth_0x557d90(undefined4 * param_1);
undefined __thiscall meth_0x557ff0(void);
undefined __thiscall meth_0x558190(int param_1, int * param_2);
undefined __thiscall meth_0x5583e0(_String_base * param_1, undefined4 param_2, undefined4 param_3, void * param_4);
undefined __thiscall meth_0x558510(int param_1, int param_2);
