typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
} cls_0x424a20;
undefined __thiscall meth_0x424a20(void);
undefined __thiscall meth_0x424a30(void);
undefined __thiscall meth_0x426ac0(void);
undefined __thiscall meth_0x429760(int param_1, int param_2, _String_base * param_3, int param_4, int param_5);
