typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    byte mbr_0x34;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
} cls_0x52e2e0;
undefined __thiscall meth_0x52d820(undefined4 * param_1, int * param_2, undefined4 * param_3);
cls_0x52e2e0 * __thiscall cls_0x52e2e0(void);
