#include "cls_0x4a67f0.h"
typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    byte mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    Gfx_AnimationObject * animation_object;
    granny_model_instance * model_instance;
    granny_track_mask * track_mask;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    byte mbr_0x2c;
    undefined None;
    undefined None;
    undefined None;
    granny_control * control;
    granny_control * control_2;
    typedef granny_int32x granny_int32 bone_count;
    granny_world_pose * world_pose;
    granny_matrix_4x4 * bone_matrices_4x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword VFX_Parameter_vftable_673a20;
    dword anim_index;
    dword mbr_0x54;
    dword VFX_Parameter_vftable_673a20_3;
    dword anim_index_3;
    dword mbr_0x60;
    typedef granny_real32 float granny_duration_2;
    bool granny_from_current_2;
    undefined None;
    undefined None;
    undefined None;
    typedef granny_int32x granny_int32 loop_count_2;
    byte mbr_0x70;
    undefined None;
    undefined None;
    undefined None;
    dword VFX_Parameter_vftable_673a20_2;
    dword anim_index_2;
    dword mbr_0x7c;
    typedef granny_real32 float granny_duration;
    bool granny_from_current;
    undefined None;
    undefined None;
    undefined None;
    typedef granny_int32x granny_int32 loop_count;
    typedef granny_real32 float speed;
    byte mbr_0x90;
    undefined None;
    undefined None;
    undefined None;
    typedef granny_real32 float seconds;
    typedef granny_real32 float seconds2;
    typedef granny_int32x granny_int32 loop_count_3;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    cls_0x4a67f0 cls_0x4a67f0;
    dword mbr_0xbc;
    dword mbr_0xc0;
    byte mbr_0xc4;
} cls_0x4a5be0;
undefined __thiscall meth_0x4a4c90(granny_real32 Duration, char param_2);
undefined __thiscall meth_0x4a55d0(uint param_1);
undefined4 __thiscall meth_0x4a5640(undefined4 param_1, uint param_2, uint param_3, undefined4 param_4, undefined param_5, undefined4 param_6);
cls_0x4a5be0 * __thiscall cls_0x4a5be0(undefined4 animation_object);
undefined __thiscall meth_0x4a5d70(void);
int __thiscall meth_0x4a5ea0(uint param_1);
undefined __thiscall meth_0x4a5f20(void);
undefined __thiscall meth_0x4a5f60(int * * param_1);
undefined __thiscall meth_0x4a6070(void);
undefined __thiscall meth_0x4a62b0(int * * seconds);
cls_0x4a5be0 * __thiscall cls_0x4a5be0(int param_1);
undefined __thiscall meth_0x548d10(undefined4 speed);
