typedef struct {
    dword mbr_0x0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    dword mbr_0x28;
} cls_0x43a420;
undefined __thiscall meth_0x43a420(int * param_1);
undefined __thiscall meth_0x43ae90(int * param_1, uint param_2);
