typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x10;
    byte mbr_0x14;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x28;
    dword mbr_0x2c;
} cls_0x420270;
undefined __thiscall meth_0x420270(void);
undefined __thiscall meth_0x505cd0(void);
