typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x30;
} cls_0x53a510;
undefined __thiscall meth_0x53a4f0(void);
cls_0x53a510 * __thiscall cls_0x53a510(void);
MCIERROR __thiscall meth_0x53a550(void);
undefined __thiscall meth_0x53a640(void);
undefined __thiscall meth_0x53a6d0(void);
