typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    dword mbr_0x28;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x30;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x50;
} cls_0x423e20;
undefined __thiscall meth_0x423e20(char param_1);
undefined __thiscall meth_0x423e50(void);
undefined __thiscall meth_0x423ec0(void);
undefined __thiscall meth_0x423f40(void);
undefined __thiscall meth_0x424140(void);
undefined __thiscall meth_0x424340(void);
undefined __thiscall meth_0x424520(void);
