typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
} cls_0x539fb0;
int __thiscall meth_0x539fb0(void);
undefined4 __thiscall meth_0x53a080(undefined4 param_1, char param_2);
undefined __thiscall meth_0x53a0e0(char param_1);
undefined __thiscall meth_0x53a100(void);
