typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
} cls_0x53b440;
bool __thiscall meth_0x53b440(uint param_1);
