typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    byte mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x68;
    dword mbr_0x6c;
} cls_0x474d1a;
undefined __thiscall meth_0x474d1a(undefined4 param_1, uint param_2);
int __thiscall meth_0x477c4c(uint param_1, uint param_2);
undefined4 __thiscall meth_0x478f13(void);
undefined __thiscall meth_0x479039(void * param_1);
int __thiscall meth_0x47c653(void * param_1);
int __thiscall meth_0x47c823(void * param_1);
undefined __thiscall meth_0x47db36(uint * param_1, uint * param_2, uint * param_3, uint * param_4, int * * param_5, int * param_6, uint * param_7);
undefined4 __thiscall meth_0x47ef19(void);
undefined4 __thiscall meth_0x480849(void);
