typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
} cls_0x4ac210;
undefined __thiscall meth_0x4ac210(void);
