typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    byte mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x3c;
    byte mbr_0x40;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    byte mbr_0x48;
    byte mbr_0x49;
    undefined None;
    undefined None;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x6c;
    dword mbr_0x70;
    byte mbr_0x74;
} cls_0x490150;
undefined __thiscall meth_0x490150(void);
undefined __thiscall meth_0x490510(int * param_1);
undefined __thiscall meth_0x4911b0(int param_1);
undefined __thiscall meth_0x4913e0(int * param_1);
undefined __thiscall meth_0x491b10(void);
undefined __thiscall meth_0x491fc0(void);
undefined __thiscall meth_0x4931e0(void);
undefined __thiscall meth_0x494b40(void);
undefined __thiscall meth_0x494ca0(char param_1);
