typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0x4;
    byte mbr_0x5;
    byte mbr_0x6;
    byte mbr_0x7;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    byte mbr_0x28;
} cls_0x41d060;
undefined __thiscall meth_0x41d060(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined __thiscall meth_0x4ae0a0(undefined4 * param_1);
undefined __thiscall meth_0x4ae100(undefined param_1, undefined param_2, undefined param_3, undefined param_4);
undefined __thiscall meth_0x4ae280(void);
undefined __thiscall meth_0x4aed50(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined param_5, undefined param_6, undefined param_7, undefined param_8, undefined param_9, undefined param_10, undefined param_11, undefined param_12);
