#include "VFX_Parameter.h"
typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    VFX_Parameter VFX_Parameter;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xd8;
    dword mbr_0xdc;
    dword mbr_0xe0;
    dword mbr_0xe4;
    dword mbr_0xe8;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    dword mbr_0xfc;
    dword mbr_0x100;
    dword mbr_0x104;
    byte mbr_0x108;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x110;
    dword mbr_0x114;
    dword mbr_0x118;
    dword mbr_0x11c;
    dword mbr_0x120;
    dword mbr_0x124;
    dword mbr_0x128;
    dword mbr_0x12c;
    dword mbr_0x130;
    dword mbr_0x134;
    dword mbr_0x138;
    dword mbr_0x13c;
    dword mbr_0x140;
    dword mbr_0x144;
    dword mbr_0x148;
    dword mbr_0x14c;
    dword mbr_0x150;
    dword mbr_0x154;
    dword mbr_0x158;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x1c8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x204;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0x240;
} cls_0x50db20;
int __thiscall meth_0x401440(void);
undefined __thiscall meth_0x401490(int param_1);
undefined __thiscall meth_0x4014b0(char param_1);
undefined __thiscall meth_0x401510(void);
bool __thiscall meth_0x401940(uint param_1, char param_2);
_String_base * __thiscall meth_0x401a40(uint param_1, uint param_2);
_String_base * __thiscall meth_0x401b20(_String_base * param_1, uint param_2, uint param_3);
_String_base * __thiscall meth_0x401bd0(char * param_1, uint param_2);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x40acc0(int * param_1);
_String_base * __thiscall meth_0x4174f0(uint param_1, int * * param_2, uint param_3, uint param_4, uint param_5);
_String_base * __thiscall meth_0x417870(uint param_1, int * * param_2, int * * param_3, int * * param_4);
uint __thiscall meth_0x41e4b0(uint param_1, uint param_2, _String_base * param_3, uint param_4);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
_String_base * __thiscall meth_0x425bd0(uint param_1);
int __thiscall meth_0x430800(void);
undefined4 __thiscall meth_0x4324b0(uint param_1);
undefined __thiscall meth_0x432510(void);
undefined __thiscall meth_0x432f60(_String_base * param_1, _String_base * param_2, _String_base * param_3);
undefined __thiscall meth_0x433430(_String_base * param_1, undefined4 param_2, void * param_3);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x45ce10(void);
_String_base * __thiscall meth_0x4971c0(uint param_1, undefined param_2);
cls_0x50db20 * __thiscall cls_0x50db20(uint param_1, undefined param_2);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x4b2ec0(void);
undefined __thiscall meth_0x4b5e60(undefined4 * param_1);
undefined __thiscall meth_0x4b5eb0(uint param_1, char param_2, char param_3);
undefined __thiscall meth_0x4b5f90(uint param_1);
undefined __thiscall meth_0x4b6010(void);
undefined __thiscall meth_0x4c5dc0(int * param_1, _String_base * param_2, _String_base * param_3);
undefined __thiscall meth_0x4c60a0(_String_base * param_1);
undefined __thiscall meth_0x4c8610(undefined param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5);
undefined __thiscall meth_0x4c8650(undefined param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5);
undefined __thiscall meth_0x4c8690(undefined param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7);
undefined __thiscall meth_0x4c86e0(undefined param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6);
undefined __thiscall meth_0x4cb240(void);
undefined __thiscall meth_0x4cd070(uint param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x4d05e0(void);
undefined __thiscall meth_0x4d1290(FILE * param_1);
undefined __thiscall meth_0x4d16a0(int param_1, int * param_2);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
undefined __thiscall meth_0x4d5100(void);
cls_0x50db20 * __thiscall cls_0x50db20(int param_1);
int __thiscall meth_0x4d7bc0(int param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, int param_2);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, _String_base * param_2);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, undefined * param_2);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
undefined __thiscall meth_0x4f9e60(void);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, int param_2);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall ~cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1, _String_base * param_2);
void * __thiscall meth_0x571110(_String_base * param_1);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x592880(uint param_1);
cls_0x50db20 * __thiscall cls_0x50db20(int param_1, int param_2);
undefined __thiscall meth_0x592fb0(uint param_1, int param_2, int param_3, int param_4);
cls_0x50db20 * __thiscall cls_0x50db20(void);
undefined __thiscall meth_0x594370(int param_1, int param_2);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(_String_base * param_1);
undefined __thiscall meth_0x5a9ab0(undefined4 param_1, undefined4 * param_2, void * param_3, undefined4 param_4, undefined4 param_5, int param_6, uint param_7, uint param_8, undefined4 * param_9, undefined4 param_10, undefined4 param_11, undefined4 param_12, int param_13, uint param_14, uint param_15);
long __thiscall meth_0x5a9e60(undefined4 param_1, void * param_2);
cls_0x50db20 * __thiscall cls_0x50db20(void);
cls_0x50db20 * __thiscall cls_0x50db20(undefined4 * param_1, uint param_2);
