#include "cls_0x496bd0.h"
#include "cls_0x4d8d70.h"
typedef struct {
    cls_0x496bd0 cls_0x496bd0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    cls_0x4d8d70 cls_0x4d8d70;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} cls_0x40a220;
cls_0x40a220 * __thiscall cls_0x40a220(void);
cls_0x40a220 * __thiscall cls_0x40a220(int param_1);
undefined __thiscall meth_0x497fb0(char * param_1, uint param_2);
int * __thiscall meth_0x498120(int * param_1);
int * __thiscall meth_0x4984e0(int param_1, undefined4 param_2);
undefined4 * __thiscall meth_0x498550(undefined4 * param_1);
int * __thiscall meth_0x499040(undefined4 param_1, int param_2);
cls_0x40a220 * __thiscall cls_0x40a220(int param_1);
void * __thiscall meth_0x4e3260(_String_base * param_1);
int * __thiscall meth_0x5a4b80(undefined * param_1, int param_2, byte param_3);
