typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    byte mbr_0x28;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x54;
    dword mbr_0x58;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xb8;
} cls_0x4b28a0;
undefined __thiscall meth_0x4b28a0(undefined4 * param_1, undefined4 * param_2);
undefined __thiscall meth_0x4b28c0(undefined4 * param_1, undefined4 * param_2);
undefined __thiscall meth_0x4b28e0(undefined4 * param_1);
undefined __thiscall Set_mbr_0x4_to_1(void);
undefined4 __thiscall meth_0x4b2ad0(int * param_1);
bool __thiscall meth_0x4b2c10(void);
int __thiscall meth_0x4b2c20(undefined param_1, undefined4 param_2, undefined4 param_3);
undefined4 __thiscall meth_0x4b2d40(HWND param_1);
int __thiscall meth_0x4b2f30(undefined4 param_1, int * param_2, int * param_3);
int __thiscall meth_0x4b2f80(void);
undefined __thiscall meth_0x4b2fe0(undefined param_1, undefined1 param_2);
undefined4 __thiscall meth_0x4b3000(void);
undefined __thiscall meth_0x4b3040(int * param_1, undefined4 * param_2);
undefined __thiscall meth_0x4b3430(int * param_1);
undefined __thiscall meth_0x4b34b0(int * param_1);
int __thiscall meth_0x4b3500(undefined4 param_1, int * param_2, int * param_3);
int __thiscall meth_0x4b3570(void);
undefined __thiscall meth_0x4b35f0(void);
undefined4 __thiscall meth_0x4b3780(undefined4 param_1, int * param_2);
undefined __thiscall meth_0x4b37f0(void);
undefined4 __thiscall meth_0x4b3920(undefined4 param_1);
bool __thiscall meth_0x4b40a0(undefined4 param_1, char param_2, undefined4 param_3);
undefined __thiscall meth_0x4b40f0(char param_1, undefined4 param_2);
undefined __thiscall meth_0x4b4dd0(int * param_1);
undefined __thiscall meth_0x4b4e60(int * param_1);
undefined __thiscall meth_0x4b4f00(int param_1);
undefined __thiscall meth_0x4b58d0(undefined4 * param_1, int param_2, int param_3, int param_4);
undefined4 __thiscall meth_0x619b38(void);
