#include "cls_0x4abc60.h"
typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    cls_0x4abc60 cls_0x4abc60;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
    dword mbr_0x80;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    byte mbr_0x94;
} cls_0x515040;
undefined __thiscall meth_0x41f200(void);
undefined4 __thiscall meth_0x41f630(int param_1);
undefined __thiscall meth_0x41fdf0(void);
undefined __thiscall meth_0x4b6670(void);
undefined __thiscall meth_0x4c0ea0(void);
undefined __thiscall meth_0x4e42c0(void);
undefined __thiscall meth_0x4e6140(void);
cls_0x515040 * __thiscall cls_0x515040(void);
undefined __thiscall meth_0x5150c0(void);
