typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    byte mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    byte mbr_0x48;
} cls_0x5813e0;
undefined4 __thiscall meth_0x5813e0(void);
undefined4 __thiscall meth_0x581400(void);
undefined4 __thiscall meth_0x581420(void);
int __thiscall meth_0x581430(void);
undefined __thiscall meth_0x5817a0(uint param_1);
