typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
} cls_0x46a8e0;
undefined __thiscall meth_0x46a8e0(int param_1, void * param_2);
int __thiscall meth_0x55fea0(int param_1);
