typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
} cls_0x5aa3d0;
cls_0x5aa3d0 * __thiscall cls_0x5aa3d0(void);
