typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
} cls_0x581330;
undefined __thiscall meth_0x581330(void);
