#include "G3D_Transform.h"
typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    G3D_Transform G3D_Transform;
} cls_0x4cb300;
cls_0x4cb300 * __thiscall cls_0x4cb300(void);
cls_0x4cb300 * __thiscall ~cls_0x4cb300(void);
undefined __thiscall meth_0x4d07f0(void);
undefined __thiscall meth_0x4d09b0(FILE * param_1);
undefined __thiscall meth_0x4d09d0(int param_1, int * param_2);
