typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
} cls_0x5e8d47;
byte * * __thiscall meth_0x5e8d47(byte * param_1);
