#include "cls_0x55dd10.h"
typedef struct {
    byte mbr_0x0;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword mbr_0x4c;
    cls_0x55dd10 cls_0x55dd10;
} cls_0x55df60;
cls_0x55df60 * __thiscall cls_0x55df60(void);
undefined __thiscall meth_0x55dfc0(void);
cls_0x55df60 * __thiscall cls_0x55df60(undefined * param_1);
