typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x30;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
} cls_0x48fb60;
undefined __thiscall meth_0x48f870(void);
undefined __thiscall meth_0x48f940(undefined4 param_1, undefined4 param_2);
cls_0x48fb60 * __thiscall cls_0x48fb60(void);
undefined __thiscall meth_0x48fe50(void);
undefined __thiscall meth_0x48fe70(undefined4 param_1, undefined4 param_2);
undefined __thiscall meth_0x48fee0(undefined4 * param_1, double * param_2);
undefined __thiscall meth_0x48ff20(void);
undefined __thiscall meth_0x48ff70(undefined4 param_1, undefined4 param_2);
undefined __thiscall meth_0x48ffd0(double * param_1);
cls_0x48fb60 * __thiscall cls_0x48fb60(undefined4 param_1, undefined4 param_2);
