typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
} cls_0x475a80;
cls_0x475a80 * __thiscall cls_0x475a80(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined __thiscall meth_0x475aa1(void);
