typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x68;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x7c;
    dword mbr_0x80;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xb4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    byte mbr_0xd0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0xd8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xdc;
    dword mbr_0xe0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xe8;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    dword mbr_0xfc;
    dword mbr_0x100;
    dword mbr_0x104;
    dword mbr_0x108;
    dword mbr_0x10c;
    dword mbr_0x110;
    dword mbr_0x114;
    dword mbr_0x118;
    dword mbr_0x11c;
    dword mbr_0x120;
} cls_0x424a70;
undefined __thiscall meth_0x424a70(void);
undefined __thiscall meth_0x424be0(void);
int __thiscall meth_0x424c60(void);
undefined __thiscall meth_0x424ca0(char param_1);
undefined __thiscall meth_0x424cd0(char param_1);
undefined4 __thiscall meth_0x424d40(void);
undefined4 __thiscall meth_0x424d50(void);
undefined4 __thiscall meth_0x424d60(void);
undefined4 __thiscall meth_0x424d70(void);
undefined __thiscall meth_0x425000(void);
undefined __thiscall meth_0x425020(void);
undefined __thiscall meth_0x425040(void);
undefined __thiscall meth_0x425090(void);
undefined __thiscall meth_0x4250e0(void);
undefined __thiscall meth_0x425100(void);
undefined __thiscall meth_0x425120(void);
undefined __thiscall meth_0x425520(int param_1);
undefined __thiscall meth_0x425b50(int * param_1);
undefined __thiscall meth_0x425bb0(void);
undefined __thiscall meth_0x426c20(undefined4 param_1);
undefined __thiscall meth_0x426ce0(undefined param_1, undefined4 param_2);
undefined __thiscall meth_0x426e40(int param_1);
undefined __thiscall meth_0x426f80(void);
undefined __thiscall meth_0x427040(int param_1, int param_2);
undefined __thiscall meth_0x4271a0(int * param_1);
undefined __thiscall meth_0x427480(int param_1);
undefined __thiscall meth_0x427560(void);
undefined __thiscall meth_0x427910(void);
undefined __thiscall meth_0x427a40(void);
undefined __thiscall meth_0x428250(int param_1);
undefined __thiscall meth_0x4284b0(int param_1);
undefined __thiscall meth_0x4285d0(int param_1);
undefined __thiscall meth_0x4286f0(int param_1);
undefined __thiscall meth_0x428b60(undefined4 param_1, undefined4 param_2, uint param_3);
undefined __thiscall meth_0x429900(int param_1, int param_2);
undefined __thiscall meth_0x429ab0(int * param_1);
undefined __thiscall meth_0x429b20(void);
undefined4 __thiscall meth_0x429dd0(void);
undefined __thiscall meth_0x429e20(undefined4 param_1, uint param_2);
undefined __thiscall meth_0x42a190(void);
undefined __thiscall meth_0x42a200(void);
undefined __thiscall meth_0x42c6d0(void);
undefined __thiscall meth_0x42c860(void);
undefined __thiscall meth_0x42cdb0(void);
undefined __thiscall meth_0x42d130(void);
undefined __thiscall meth_0x42d4c0(void);
undefined __thiscall meth_0x42d880(void);
undefined __thiscall meth_0x42dc40(void);
undefined __thiscall meth_0x42e070(void);
undefined __thiscall meth_0x42e4a0(void);
undefined __thiscall meth_0x42e870(int param_1, char param_2);
undefined __thiscall meth_0x42f5a0(void);
undefined __thiscall meth_0x42f710(void);
undefined __thiscall meth_0x42f740(int param_1);
undefined __thiscall meth_0x42f9e0(void);
undefined __thiscall meth_0x42fd60(int param_1, uint param_2, void * param_3, uint param_4, undefined4 param_5, uint param_6);
