typedef struct {
    dword mbr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x38;
    dword mbr_0x3c;
} cls_0x474824;
cls_0x474824 * __thiscall cls_0x474824(uint param_1);
undefined __thiscall meth_0x4748ec(int param_1, undefined4 * param_2);
undefined __thiscall meth_0x474908(int param_1, undefined4 param_2);
undefined4 __thiscall meth_0x474924(uint param_1);
