typedef struct {
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4;
    word mbr_0x8;
    word mbr_0xa;
    word mbr_0xc;
    word mbr_0xe;
    dword mbr_0x10;
    word mbr_0x14;
    word mbr_0x16;
    word mbr_0x18;
    undefined None;
    undefined None;
    dword mbr_0x1c;
    dword mbr_0x20;
} cls_0x475d0f;
int __thiscall meth_0x475d0f(void);
undefined __thiscall meth_0x475fee(ushort param_1);
undefined __thiscall meth_0x476072(ushort param_1);
undefined __thiscall meth_0x4760be(short param_1);
undefined4 __thiscall meth_0x47a934(ushort param_1, ushort param_2, char param_3);
undefined __thiscall meth_0x47aa30(ushort param_1);
undefined4 __thiscall meth_0x47aaab(ushort param_1);
