#include "CSoundFile.h"
typedef struct {
    CSoundFile CSoundFile;
    dword mbr_0x2c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x3c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
} CMasterJumplist;
undefined __thiscall meth_0x4c7180(undefined * param_1, int param_2);
undefined __thiscall meth_0x4c7e80(void);
CMasterJumplist * __thiscall CMasterJumplist(void);
undefined __thiscall meth_0x539190(void);
CMasterJumplist * __thiscall ~CMasterJumplist(void);
undefined __thiscall virt_meth_0x539a00(undefined4 * param_1, undefined4 param_2);
typedef struct {
    virt_meth_0x4c8540 * virt_meth_0x4c8540_0;
    virt_meth_0x539a00 * virt_meth_0x539a00_4;
} CMasterJumplist::vftable_67d1f0;
