typedef struct {
    CStoreItem::vftable_6a379c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
} CStoreItem;
CStoreItem * __thiscall ~CStoreItem(void);
undefined4 * __thiscall virt_meth_0x5a2100(byte param_1);
CStoreItem * __thiscall CStoreItem(void);
typedef struct {
    virt_meth_0x5a2100 * virt_meth_0x5a2100_0;
} CStoreItem::vftable_6a379c;
