#include "Interface.h"
#include "CSound.h"
typedef struct {
    Interface Interface;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    CSound CSound;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x1a0;
    dword mbr_0x1a4;
    dword mbr_0x1a8;
    dword mbr_0x1ac;
    dword mbr_0x1b0;
    dword mbr_0x1b4;
} CWorldContainerInterface;
undefined __thiscall meth_0x4574b0(void);
undefined4 __thiscall meth_0x4574f0(int param_1);
undefined __thiscall meth_0x457520(void);
undefined __thiscall virt_meth_0x4575d0(int * param_1, int * param_2);
undefined __thiscall meth_0x457a10(void);
CWorldContainerInterface * __thiscall ~CWorldContainerInterface(void);
CWorldContainerInterface * __thiscall CWorldContainerInterface(_String_base * param_1);
int * __thiscall virt_meth_0x458030(byte param_1);
int __thiscall Get_Interface_mbr_0x24(void);
int __thiscall meth_0x4952b0(undefined4 param_1, undefined4 param_2, undefined4 param_3);
typedef struct {
    virt_meth_0x458030 * virt_meth_0x458030_0;
    FUN_004953c0 * FUN_004953c0_4;
    virt_meth_0x4575d0 * virt_meth_0x4575d0_8;
    virt_meth_0x4577d0 * virt_meth_0x4577d0_12;
    virt_meth_0x404b70 * virt_meth_0x404b70_16;
    virt_meth_0x430790 * virt_meth_0x430790_20;
} CWorldContainerInterface::vftable_65cb9c;
