#include "CEngineInterface.h"
typedef struct {
    CEngineInterface CEngineInterface;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
} EditTokenInterface;
EditTokenInterface * __thiscall EditTokenInterface(_String_base * param_1);
int * __thiscall virt_meth_0x5b3fd0(byte param_1);
undefined __thiscall meth_0x5b3ff0(void);
undefined __thiscall meth_0x5b4130(void);
undefined __thiscall virt_meth_0x5b42a0(int * param_1, int * param_2);
typedef struct {
    virt_meth_0x5b3fd0 * virt_meth_0x5b3fd0_0;
    FUN_004953c0 * FUN_004953c0_4;
    virt_meth_0x5b42a0 * virt_meth_0x5b42a0_8;
    virt_meth_0x404b70 * virt_meth_0x404b70_12;
    virt_meth_0x404b70 * virt_meth_0x404b70_16;
    virt_meth_0x580360 * virt_meth_0x580360_20;
} EditTokenInterface::vftable_6ab354;
