#include "Entity.h"
typedef struct {
    GameEntity::vftable_666130 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    dword mbr_0x98;
    byte mbr_0x9c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    Entity Entity;
} GameEntity;
undefined4 __fastcall QueryDefaultAnimation(int param_1);
undefined4 __thiscall Queue_Idle(undefined4 param_1);
int __thiscall QueueToCombat(void);
undefined4 __thiscall Queue_Unequip(void);
undefined __thiscall SetWeaponStance(int param_1);
undefined4 __thiscall Queue_Equip(void);
int __thiscall QueueToDefault(void);
int __thiscall Queue_To_Crouch(void);
int __thiscall Queue_Walk(void);
int __thiscall Queue_Limp(void);
int __thiscall QueueAnimEvent(int param_1, undefined4 param_2);
GameEntity * __thiscall GameEntity(int param_1);
typedef struct {
    virt_meth_0x4080c0 * virt_meth_0x4080c0_0;
} GameEntity::vftable_666130;
