#include "Gfx_ParticleInfoBase.h"
#include "cls_0x515ed0.h"
typedef struct {
    Gfx_ParticleInfoBase Gfx_ParticleInfoBase;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    cls_0x515ed0 cls_0x515ed0;
    byte mbr_0xd0;
} Gfx_ParticleInfo;
undefined __thiscall meth_0x513af0(int param_1);
Gfx_ParticleInfo * __thiscall Gfx_ParticleInfo(void);
Gfx_ParticleInfo * __thiscall ~Gfx_ParticleInfo(void);
int * __thiscall virt_meth_0x514c80(byte param_1);
Gfx_ParticleInfo * __thiscall Gfx_ParticleInfo(int param_1);
typedef struct {
    virt_meth_0x514c80 * virt_meth_0x514c80_0;
} Gfx_ParticleInfo::vftable_675da0;
