typedef struct {
    Gfx_Texture::vftable_677370 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
} Gfx_Texture;
Gfx_Texture * __thiscall Gfx_Texture(int param_1);
undefined __thiscall meth_0x51f280(void);
undefined4 * __thiscall virt_meth_0x51f550(byte param_1);
int * __thiscall meth_0x520100(undefined4 param_1, void * param_2);
undefined4 __thiscall meth_0x534bf0(int param_1);
undefined __thiscall meth_0x534ce0(void);
int * __thiscall CreateTexture(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, int param_7);
int * __thiscall LoadTextureFrameFromBuffer(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined4 param_9);
int __thiscall LockRect(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, int param_5);
undefined __thiscall CopyRect(undefined4 param_1, undefined4 param_2, int param_3, undefined4 param_4, undefined4 param_5, int param_6, int param_7);
undefined __thiscall Clear(void);
int __thiscall UpdateDefaultTexture(int param_1, int param_2, int param_3);
undefined __thiscall meth_0x535370(int param_1);
undefined __thiscall LoadTextureFrameFromFile(undefined4 param_1, int * param_2, undefined4 param_3, void * param_4, undefined4 param_5, undefined4 param_6, uint param_7, undefined4 param_8, uint param_9, undefined4 param_10, undefined4 param_11, undefined4 param_12, undefined4 param_13, int param_14);
undefined __thiscall meth_0x535850(char * param_1, uint param_2, undefined4 param_3, uint param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8);
undefined __thiscall meth_0x535a80(char * param_1, uint param_2, undefined4 param_3, uint param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8);
undefined4 __thiscall meth_0x535b40(undefined4 param_1, undefined4 * param_2);
undefined __thiscall meth_0x535cc0(undefined4 param_1, undefined4 * param_2);
typedef struct {
    virt_meth_0x51f550 * virt_meth_0x51f550_0;
    virt_meth_0x534c40 * virt_meth_0x534c40_4;
} Gfx_Texture::vftable_677370;
