#include "Gfx_NodeAttribute.h"
typedef struct {
    Gfx_NodeAttribute Gfx_NodeAttribute;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    byte mbr_0x34;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x38;
    dword mbr_0x3c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x64;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x74;
    dword mbr_0x78;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x80;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x90;
    dword mbr_0x94;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x9c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
    byte mbr_0xbc;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    dword mbr_0xd0;
    dword mbr_0xd4;
    byte mbr_0xd8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xdc;
    dword mbr_0xe0;
    dword mbr_0xe4;
    dword mbr_0xe8;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    dword mbr_0xfc;
    dword mbr_0x100;
    dword mbr_0x104;
    dword mbr_0x108;
    dword mbr_0x10c;
    dword mbr_0x110;
    dword mbr_0x114;
    dword mbr_0x118;
    dword mbr_0x11c;
    dword mbr_0x120;
    dword mbr_0x124;
    dword mbr_0x128;
    dword mbr_0x12c;
    dword mbr_0x130;
    dword mbr_0x134;
    dword mbr_0x138;
    dword mbr_0x13c;
    dword mbr_0x140;
    dword mbr_0x144;
    dword mbr_0x148;
    dword mbr_0x14c;
    dword mbr_0x150;
    dword mbr_0x154;
    dword mbr_0x158;
    dword mbr_0x15c;
    dword mbr_0x160;
    dword mbr_0x164;
    dword mbr_0x168;
    dword mbr_0x16c;
    dword mbr_0x170;
    byte mbr_0x174;
} Gfx_Water;
undefined __thiscall meth_0x49eac0(undefined4 param_1, void * param_2);
undefined __thiscall meth_0x49eb20(undefined4 param_1, void * param_2);
undefined __thiscall meth_0x49eb80(undefined4 param_1, void * param_2);
int __thiscall meth_0x51c8e0(uint param_1, int param_2);
undefined __thiscall meth_0x51c990(uint param_1, int param_2, float param_3);
undefined __thiscall meth_0x51c9e0(uint param_1, int param_2, float param_3);
undefined __thiscall meth_0x51cab0(float param_1, float param_2, float param_3, int param_4);
undefined __thiscall meth_0x51ccc0(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8);
undefined __thiscall meth_0x51cd20(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined4 param_9, undefined4 param_10, undefined4 param_11, undefined4 param_12);
undefined __thiscall meth_0x51cda0(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8);
undefined __thiscall meth_0x51d840(void);
Gfx_Water * __thiscall Gfx_Water(void);
Gfx_Water * __thiscall ~Gfx_Water(void);
int * __thiscall virt_meth_0x51e900(byte param_1);
typedef struct {
    virt_meth_0x51e900 * virt_meth_0x51e900_0;
    virt_meth_0x51ce00 * virt_meth_0x51ce00_4;
} Gfx_Water::vftable_675dd0;
