#include "Gfx_NodeAttribute.h"
typedef struct {
    Gfx_NodeAttribute Gfx_NodeAttribute;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
    dword mbr_0x80;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    byte mbr_0x98;
    byte mbr_0x99;
    undefined None;
    undefined None;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    byte mbr_0xa8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xac;
    byte mbr_0xb0;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xb4;
    dword mbr_0xb8;
    dword mbr_0xbc;
    byte mbr_0xc0;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc4;
} Gfx_SkinMeshPkt;
Gfx_SkinMeshPkt * __thiscall Gfx_SkinMeshPkt(int param_1);
int * __thiscall virt_meth_0x49e2a0(byte param_1);
Gfx_SkinMeshPkt * __thiscall ~Gfx_SkinMeshPkt(void);
undefined __thiscall meth_0x49e3d0(void);
undefined __thiscall meth_0x507b30(void);
typedef struct {
    virt_meth_0x49e2a0 * virt_meth_0x49e2a0_0;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_4;
} Gfx_SkinMeshPkt::vftable_66b4a0;
