#include "Gfx_NodeAttribute.h"
#include "cls_0x514000.h"
typedef struct {
    Gfx_NodeAttribute Gfx_NodeAttribute;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    byte mbr_0x54;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x58;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
    dword mbr_0xbc;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    dword mbr_0xd0;
    dword mbr_0xd4;
    dword mbr_0xd8;
    dword mbr_0xdc;
    dword mbr_0xe0;
    dword mbr_0xe4;
    dword mbr_0xe8;
    dword mbr_0xec;
    byte mbr_0xf0;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xf4;
    byte mbr_0xf8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xfc;
    byte mbr_0x100;
    byte mbr_0x101;
    undefined None;
    undefined None;
    dword mbr_0x104;
    dword mbr_0x108;
    cls_0x514000 cls_0x514000;
    dword mbr_0x6bc;
    byte mbr_0x6c0;
    byte mbr_0x6c1;
    byte mbr_0x6c2;
    byte mbr_0x6c3;
    byte mbr_0x6c4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    byte mbr_0x6f8;
    byte mbr_0x6f9;
    byte mbr_0x6fa;
    undefined None;
    dword mbr_0x6fc;
    dword mbr_0x700;
    dword mbr_0x704;
    dword mbr_0x708;
    dword mbr_0x70c;
    dword mbr_0x710;
    dword mbr_0x714;
    dword mbr_0x718;
    dword mbr_0x71c;
    dword mbr_0x720;
} Gfx_ParticleSystem;
undefined __thiscall meth_0x513070(undefined4 * param_1);
undefined __thiscall meth_0x513410(float10 * param_1, float10 * * param_2, undefined4 * param_3, undefined4 * param_4, undefined4 * param_5, float * param_6, float * param_7, float * param_8, float * param_9, float * param_10, float * param_11, float * param_12, float * param_13);
undefined __thiscall meth_0x5138e0(undefined param_1, undefined4 param_2);
undefined __thiscall meth_0x513bf0(undefined4 param_1, int param_2, float * param_3, float * param_4, float param_5);
undefined __thiscall meth_0x514410(int param_1);
undefined __thiscall meth_0x5144e0(undefined4 param_1, undefined param_2, char param_3);
undefined __thiscall meth_0x5146c0(float * param_1, float * param_2);
undefined __thiscall meth_0x514ad0(void);
undefined __thiscall meth_0x514ca0(int param_1, undefined param_2, char param_3);
undefined __thiscall meth_0x514d30(void);
undefined __thiscall meth_0x515110(int * param_1, float param_2, undefined4 param_3, int param_4, int param_5, int param_6, float param_7);
undefined __thiscall meth_0x5154b0(void);
undefined __thiscall meth_0x5154d0(float10 * param_1);
undefined __thiscall meth_0x516480(void);
undefined __thiscall meth_0x5164e0(void);
undefined __thiscall meth_0x516550(void);
Gfx_ParticleSystem * __thiscall ~Gfx_ParticleSystem(void);
int * __thiscall virt_meth_0x516a20(byte param_1);
undefined __thiscall meth_0x516a40(undefined4 param_1, float10 * param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, undefined4 param_6, undefined4 param_7, undefined4 param_8, undefined param_9, undefined4 param_10, char param_11);
undefined __thiscall meth_0x516dd0(float10 * param_1);
undefined __thiscall meth_0x5185d0(int param_1, void * param_2);
undefined __thiscall meth_0x518c60(int * param_1);
undefined __thiscall meth_0x5192c0(void * param_1);
undefined __thiscall meth_0x519300(void);
undefined __thiscall meth_0x519490(int param_1, undefined4 param_2);
undefined __thiscall meth_0x519e70(undefined4 param_1);
Gfx_ParticleSystem * __thiscall Gfx_ParticleSystem(void);
undefined __thiscall meth_0x51ae20(void);
undefined __thiscall meth_0x51b1e0(void);
undefined __thiscall meth_0x51c320(undefined4 param_1);
undefined __thiscall meth_0x51c490(int param_1);
typedef struct {
    virt_meth_0x516a20 * virt_meth_0x516a20_0;
    virt_meth_0x51a6c0 * virt_meth_0x51a6c0_4;
} Gfx_ParticleSystem::vftable_675da8;
