#include "Gfx_NodeAttribute.h"
#include "cls_0x4abc60.h"
typedef struct {
    Gfx_NodeAttribute Gfx_NodeAttribute;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    cls_0x4abc60 cls_0x4abc60;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x90;
    dword mbr_0x94;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
    dword mbr_0xbc;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    dword mbr_0xd0;
    dword mbr_0xd4;
    dword mbr_0xd8;
    dword mbr_0xdc;
    dword mbr_0xe0;
    dword mbr_0xe4;
    dword mbr_0xe8;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    dword mbr_0xfc;
    dword mbr_0x100;
    dword mbr_0x104;
    dword mbr_0x108;
    dword mbr_0x10c;
    dword mbr_0x110;
    dword mbr_0x114;
    byte mbr_0x118;
} Gfx_LineSystem;
Gfx_LineSystem * __thiscall ~Gfx_LineSystem(void);
undefined4 * __thiscall virt_meth_0x50f760(byte param_1);
int __thiscall meth_0x50f780(int param_1);
Gfx_LineSystem * __thiscall Gfx_LineSystem(void);
Gfx_LineSystem * __thiscall Gfx_LineSystem(int param_1);
typedef struct {
    virt_meth_0x50f760 * virt_meth_0x50f760_0;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_4;
} Gfx_LineSystem::vftable_675d48;
