typedef struct {
    Gfx_NodeAttribute::vftable_66b488 * vftptr_0x0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x1c;
    dword mbr_0x20;
} Gfx_NodeAttribute;
Gfx_NodeAttribute * __thiscall ~Gfx_NodeAttribute(void);
typedef struct {
    virt_meth_0x6162e5 * virt_meth_0x6162e5_0;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_4;
} Gfx_NodeAttribute::vftable_66b488;
