typedef struct {
    Gfx_BaseObject::vftable_651b28 * vftptr_0x0;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
} Gfx_BaseObject;
typedef struct {
    virt_meth_0x6162e5 * virt_meth_0x6162e5_0;
    virt_meth_0x49cb90 * virt_meth_0x49cb90_4;
    virt_meth_0x424590 * virt_meth_0x424590_8;
    virt_meth_0x424570 * virt_meth_0x424570_12;
    virt_meth_0x424620 * virt_meth_0x424620_16;
    virt_meth_0x4245c0 * virt_meth_0x4245c0_20;
} Gfx_BaseObject::vftable_651b28;
