typedef struct {
    Gfx_CamCtrl::vftable_670fa8 * vftptr_0x0;
    byte mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
    dword mbr_0x80;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
    dword mbr_0xb4;
} Gfx_CamCtrl;
undefined __thiscall meth_0x424670(undefined4 param_1, float param_2, float param_3);
undefined __thiscall meth_0x4c6200(void);
undefined __thiscall meth_0x4c62f0(void);
Gfx_CamCtrl * __thiscall Gfx_CamCtrl(void);
undefined4 __thiscall virt_meth_0x529ef0(void);
typedef struct {
    virt_meth_0x6162e5 * virt_meth_0x6162e5_0;
    virt_meth_0x529ef0 * virt_meth_0x529ef0_4;
    virt_meth_0x6162e5 * virt_meth_0x6162e5_8;
} Gfx_CamCtrl::vftable_670fa8;
