typedef struct {
    Gregorian::vftable_69166c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xa0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x128;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x154;
} Gregorian;
undefined4 __thiscall Get_mbr_0x30(void);
undefined4 __thiscall Get_mbr_0x34(void);
undefined4 __thiscall Get_mbr_0x2c(void);
int __thiscall meth_0x424d80(void);
undefined4 __thiscall meth_0x424e50(int param_1);
uint __thiscall meth_0x424ec0(int * param_1, int * * param_2);
undefined __thiscall meth_0x424fc0(void);
undefined __thiscall meth_0x425200(int param_1, undefined4 param_2, undefined4 param_3);
undefined __thiscall meth_0x429b70(void);
undefined __thiscall meth_0x429b70(void);
undefined __thiscall meth_0x42a320(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);
undefined __thiscall meth_0x42a740(uint param_1);
undefined __thiscall meth_0x42a770(void);
undefined __thiscall meth_0x42ca00(int * param_1, undefined4 * param_2, undefined4 * param_3);
undefined __thiscall meth_0x42cc60(undefined4 * param_1);
undefined __thiscall meth_0x42ccf0(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4, _String_base * param_5);
undefined __thiscall meth_0x4ab680(undefined4 param_1, undefined4 param_2, int * param_3);
undefined __thiscall meth_0x4ab6c0(undefined4 param_1, undefined4 param_2);
undefined __thiscall meth_0x4b1470(undefined4 param_1);
undefined4 __thiscall meth_0x4b1490(void);
undefined __thiscall meth_0x4b14a0(uint param_1);
undefined __thiscall meth_0x4b14c0(uint param_1);
undefined __thiscall meth_0x4b1540(undefined4 param_1);
undefined __thiscall meth_0x4b1550(undefined4 * param_1, undefined4 * param_2);
undefined __thiscall meth_0x4b1570(undefined4 param_1);
undefined __thiscall meth_0x4b15a0(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
undefined __thiscall meth_0x4b6d40(int param_1, int * param_2, undefined4 param_3);
undefined __thiscall meth_0x4b6eb0(undefined4 param_1, int * param_2, undefined4 param_3, uint param_4);
undefined __thiscall meth_0x52c350(undefined4 param_1, undefined4 param_2, undefined4 param_3);
undefined4 __thiscall meth_0x52c580(int param_1);
undefined4 __thiscall meth_0x52c5d0(void);
undefined4 __thiscall meth_0x52c610(void);
undefined4 __thiscall meth_0x52c660(void);
undefined4 __thiscall meth_0x52c6c0(undefined4 param_1);
int __thiscall meth_0x52c710(void);
undefined4 __thiscall meth_0x52c960(int param_1, uint param_2, int param_3);
undefined __thiscall meth_0x52ca70(void);
bool __thiscall meth_0x52cc40(void);
undefined4 __thiscall meth_0x52cca0(uint param_1, int param_2);
undefined __thiscall meth_0x52d100(void);
Gregorian * __thiscall Gregorian(uint * param_1);
undefined __thiscall virt_meth_0x5449b0(undefined4 * param_1);
undefined4 __thiscall Get_mbr_0x24(void);
undefined4 __thiscall Get_mbr_0x28(void);
Gregorian * __thiscall ~Gregorian(void);
undefined __thiscall virt_meth_0x5a3740(uint * param_1);
undefined __thiscall virt_meth_0x5a3ab0(uint param_1);
undefined __thiscall virt_meth_0x5a3b50(uint param_1);
undefined __thiscall virt_meth_0x5a3be0(uint param_1);
undefined __thiscall virt_meth_0x5a3c60(uint param_1);
undefined __thiscall virt_meth_0x5a3ce0(void);
undefined __thiscall virt_meth_0x5a3d60(void);
undefined __thiscall virt_meth_0x5a3da0(void);
undefined __thiscall virt_meth_0x5a3dd0(void);
undefined4 __thiscall virt_meth_0x5a3eb0(uint param_1);
undefined4 __thiscall virt_meth_0x5a3f10(uint param_1);
uint __thiscall virt_meth_0x5a3f60(uint param_1);
int __thiscall virt_meth_0x5a3fa0(uint param_1);
undefined __thiscall virt_meth_0x5a4070(uint param_1);
undefined __thiscall virt_meth_0x5a40d0(uint param_1);
undefined __thiscall virt_meth_0x5a4130(uint * param_1);
undefined __thiscall virt_meth_0x5a4190(uint * param_1);
undefined __thiscall virt_meth_0x5a41f0(uint * param_1);
undefined __thiscall virt_meth_0x5a4250(uint * param_1);
typedef struct {
    virt_meth_0x5449b0 * virt_meth_0x5449b0_0;
    virt_meth_0x5449d0 * virt_meth_0x5449d0_4;
    virt_meth_0x5a3740 * virt_meth_0x5a3740_8;
    virt_meth_0x41d1d0 * virt_meth_0x41d1d0_12;
    virt_meth_0x5449e0 * virt_meth_0x5449e0_16;
    virt_meth_0x5c01a0 * virt_meth_0x5c01a0_20;
    virt_meth_0x4080c0 * virt_meth_0x4080c0_24;
    virt_meth_0x544a00 * virt_meth_0x544a00_28;
    virt_meth_0x544a10 * virt_meth_0x544a10_32;
    virt_meth_0x424a10 * virt_meth_0x424a10_36;
    virt_meth_0x41d1b0 * virt_meth_0x41d1b0_40;
    virt_meth_0x544a20 * virt_meth_0x544a20_44;
    virt_meth_0x544a30 * virt_meth_0x544a30_48;
    virt_meth_0x544a40 * virt_meth_0x544a40_52;
    virt_meth_0x544a50 * virt_meth_0x544a50_56;
    virt_meth_0x544a50 * virt_meth_0x544a50_60;
    virt_meth_0x5a3920 * virt_meth_0x5a3920_64;
    virt_meth_0x5a3960 * virt_meth_0x5a3960_68;
    virt_meth_0x5a39a0 * virt_meth_0x5a39a0_72;
    virt_meth_0x5a3ab0 * virt_meth_0x5a3ab0_76;
    virt_meth_0x5a3b50 * virt_meth_0x5a3b50_80;
    virt_meth_0x5a3be0 * virt_meth_0x5a3be0_84;
    virt_meth_0x5a3c60 * virt_meth_0x5a3c60_88;
    virt_meth_0x5a3ce0 * virt_meth_0x5a3ce0_92;
    virt_meth_0x5a3d60 * virt_meth_0x5a3d60_96;
    virt_meth_0x5a3da0 * virt_meth_0x5a3da0_100;
    virt_meth_0x5a3dd0 * virt_meth_0x5a3dd0_104;
    virt_meth_0x5a4070 * virt_meth_0x5a4070_108;
    virt_meth_0x5a3df0 * virt_meth_0x5a3df0_112;
    virt_meth_0x5a40d0 * virt_meth_0x5a40d0_116;
    virt_meth_0x5a3e20 * virt_meth_0x5a3e20_120;
    virt_meth_0x5a3eb0 * virt_meth_0x5a3eb0_124;
    virt_meth_0x5a4130 * virt_meth_0x5a4130_128;
    virt_meth_0x5a3f10 * virt_meth_0x5a3f10_132;
    virt_meth_0x5a4190 * virt_meth_0x5a4190_136;
    virt_meth_0x5a3f60 * virt_meth_0x5a3f60_140;
    virt_meth_0x5a41f0 * virt_meth_0x5a41f0_144;
    virt_meth_0x5a3fa0 * virt_meth_0x5a3fa0_148;
    virt_meth_0x5a4250 * virt_meth_0x5a4250_152;
    virt_meth_0x5a3fd0 * virt_meth_0x5a3fd0_156;
    virt_meth_0x5a4020 * virt_meth_0x5a4020_160;
} Gregorian::vftable_69166c;
