typedef struct {
    HotKeyWindowFormat::vftable_659da8 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    byte mbr_0x74;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x78;
    dword mbr_0x7c;
} HotKeyWindowFormat;
HotKeyWindowFormat * __thiscall ~HotKeyWindowFormat(void);
undefined4 * __thiscall virt_meth_0x445720(byte param_1);
HotKeyWindowFormat * __thiscall HotKeyWindowFormat(void);
typedef struct {
    virt_meth_0x445720 * virt_meth_0x445720_0;
} HotKeyWindowFormat::vftable_659da8;
