typedef struct {
    HotKeyOption::vftable_659da0 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    byte mbr_0x10;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
} HotKeyOption;
HotKeyOption * __thiscall ~HotKeyOption(void);
undefined4 * __thiscall virt_meth_0x445700(byte param_1);
HotKeyOption * __thiscall HotKeyOption(void);
typedef struct {
    virt_meth_0x445700 * virt_meth_0x445700_0;
} HotKeyOption::vftable_659da0;
