#include "cls_0x4abc60.h"
typedef struct {
    LineSystem::vftable_66dfec * vftptr_0x0;
    byte mbr_0x4;
    byte mbr_0x5;
    byte mbr_0x6;
    byte mbr_0x7;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    byte mbr_0x28;
    byte mbr_0x29;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    cls_0x4abc60 cls_0x4abc60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
    dword mbr_0xbc;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    dword mbr_0xd0;
    dword mbr_0xd4;
    dword mbr_0xd8;
    dword mbr_0xdc;
    dword mbr_0xe0;
    dword mbr_0xe4;
    dword mbr_0xe8;
    dword mbr_0xec;
    dword mbr_0xf0;
    dword mbr_0xf4;
    dword mbr_0xf8;
    byte mbr_0xfc;
} LineSystem;
undefined4 __thiscall meth_0x4adda0(int * param_1, int * param_2, int * param_3, int * param_4);
undefined __thiscall virt_meth_0x4ae120(int param_1);
LineSystem * __thiscall ~LineSystem(void);
undefined __thiscall meth_0x4ae730(void);
undefined4 * __thiscall virt_meth_0x4aec80(byte param_1);
undefined __thiscall virt_meth_0x4aeca0(void);
LineSystem * __thiscall LineSystem(void);
typedef struct {
    virt_meth_0x4aec80 * virt_meth_0x4aec80_0;
    virt_meth_0x4aeca0 * virt_meth_0x4aeca0_4;
    virt_meth_0x4ae120 * virt_meth_0x4ae120_8;
    virt_meth_0x4add40 * virt_meth_0x4add40_12;
    virt_meth_0x4add80 * virt_meth_0x4add80_16;
} LineSystem::vftable_66dfec;
