typedef struct {
    Manager::vftable_66f2cc * vftptr_0x0;
    byte mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    byte mbr_0x28;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
    dword mbr_0x5c;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x84;
    dword mbr_0x88;
    dword mbr_0x8c;
    dword mbr_0x90;
    dword mbr_0x94;
    dword mbr_0x98;
    dword mbr_0x9c;
    dword mbr_0xa0;
    dword mbr_0xa4;
    dword mbr_0xa8;
    dword mbr_0xac;
    dword mbr_0xb0;
    dword mbr_0xb4;
    dword mbr_0xb8;
} Manager;
undefined __thiscall meth_0x4b2900(void);
undefined __thiscall meth_0x4b4920(void);
Manager * __thiscall ~Manager(void);
Manager * __thiscall Manager(void);
int * * __thiscall virt_meth_0x4b58b0(byte param_1);
typedef struct {
    virt_meth_0x4b58b0 * virt_meth_0x4b58b0_0;
} Manager::vftable_66f2cc;
