typedef struct {
    MapEffect::vftable_6aaec8 * vftptr_0x0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    byte mbr_0x48;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    dword mbr_0x58;
} MapEffect;
undefined __thiscall meth_0x5b2d10(void);
undefined __thiscall meth_0x5b2da0(void);
MapEffect * __thiscall ~MapEffect(void);
MapEffect * __thiscall MapEffect(undefined4 param_1);
undefined4 * __thiscall virt_meth_0x5b3050(byte param_1);
typedef struct {
    virt_meth_0x5b3050 * virt_meth_0x5b3050_0;
} MapEffect::vftable_6aaec8;
