typedef struct {
    MapSound::vftable_6aaa7c * vftptr_0x0;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x30;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x40;
    dword mbr_0x44;
    byte mbr_0x48;
    byte mbr_0x49;
    undefined None;
    undefined None;
    dword mbr_0x4c;
} MapSound;
undefined __thiscall meth_0x5b29d0(void);
undefined __thiscall meth_0x5b2a00(void);
MapSound * __thiscall MapSound(void);
MapSound * __thiscall ~MapSound(void);
undefined4 * __thiscall virt_meth_0x5b2b80(byte param_1);
typedef struct {
    virt_meth_0x5b2b80 * virt_meth_0x5b2b80_0;
} MapSound::vftable_6aaa7c;
