typedef struct {
    Script_Small::vftable_6a539c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x1c;
    dword mbr_0x20;
    byte mbr_0x24;
    byte mbr_0x25;
    dword mbr_0x26;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc0;
    dword mbr_0xc4;
    dword mbr_0xc8;
    dword mbr_0xcc;
    dword mbr_0xd0;
    dword mbr_0xd4;
    dword mbr_0xd8;
    dword mbr_0xdc;
} Script_Small;
undefined __thiscall virt_meth_0x5a58c0(char * param_1, int * * param_2);
Script_Small * __thiscall Script_Small(undefined4 param_1);
undefined __thiscall virt_meth_0x5a72f0(void);
Script_Small * __thiscall ~Script_Small(void);
undefined4 * __thiscall virt_meth_0x5a78e0(byte param_1);
undefined __cdecl Debugger(int * param_1);
undefined __thiscall Load(int * param_1, char param_2);
typedef struct {
    virt_meth_0x5a78e0 * virt_meth_0x5a78e0_0;
    virt_meth_0x5a8880 * virt_meth_0x5a8880_4;
    virt_meth_0x5a72f0 * virt_meth_0x5a72f0_8;
    virt_meth_0x5a4a80 * virt_meth_0x5a4a80_12;
    virt_meth_0x5a4390 * virt_meth_0x5a4390_16;
    virt_meth_0x5a5a90 * virt_meth_0x5a5a90_20;
    virt_meth_0x5a58c0 * virt_meth_0x5a58c0_24;
    virt_meth_0x5a43c0 * virt_meth_0x5a43c0_28;
    virt_meth_0x5a4450 * virt_meth_0x5a4450_32;
    virt_meth_0x5a44b0 * virt_meth_0x5a44b0_36;
    virt_meth_0x5a5600 * virt_meth_0x5a5600_40;
    virt_meth_0x5a73c0 * virt_meth_0x5a73c0_44;
} Script_Small::vftable_6a539c;
