typedef struct {
    VFX_ParameterHolder::vftable_67390c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    dword mbr_0xc;
    dword mbr_0x10;
    dword mbr_0x14;
    dword mbr_0x18;
    dword mbr_0x1c;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x30;
} VFX_ParameterHolder;
uint __thiscall virt_meth_0x4f9d40(int param_1, int * param_2);
undefined __thiscall meth_0x4fa3c0(undefined4 * param_1);
undefined __thiscall meth_0x4fa880(void);
VFX_ParameterHolder * __thiscall ~VFX_ParameterHolder(void);
VFX_ParameterHolder * __thiscall VFX_ParameterHolder(void);
int * __thiscall virt_meth_0x4fadb0(byte param_1);
undefined __thiscall meth_0x4fadd0(undefined4 * param_1, int param_2);
undefined __thiscall virt_meth_0x4faf20(int param_1, int * param_2);
undefined __thiscall meth_0x5011a0(void);
typedef struct {
    virt_meth_0x4fadb0 * virt_meth_0x4fadb0_0;
    virt_meth_0x4faf20 * virt_meth_0x4faf20_4;
    virt_meth_0x4f9d40 * virt_meth_0x4f9d40_8;
} VFX_ParameterHolder::vftable_67390c;
