typedef struct {
    VFX_Parameter::vftable_673a20 * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
} VFX_Parameter;
undefined4 * __thiscall meth_0x4339b0(int param_1);
undefined __thiscall meth_0x45c700(int * param_1);
undefined __thiscall meth_0x45ceb0(undefined4 param_1, int * * param_2);
undefined __thiscall meth_0x45d190(void);
undefined __thiscall meth_0x45d1d0(int * * param_1, int * * param_2, int * * param_3);
undefined __thiscall meth_0x45d290(void);
undefined __thiscall meth_0x4b92f0(int * param_1);
undefined __thiscall meth_0x4bd260(int * * param_1, char param_2, int * * param_3, undefined4 * param_4);
undefined __thiscall meth_0x4bd700(undefined4 * param_1, int * * param_2);
undefined __thiscall meth_0x4bd7c0(undefined4 param_1, int * * param_2);
undefined __thiscall meth_0x4bdaa0(void);
int __thiscall meth_0x4bdd20(int * * param_1);
undefined __thiscall meth_0x4bddb0(int * * param_1, int * * param_2, int * * param_3);
undefined __thiscall meth_0x4bde70(void);
undefined __thiscall meth_0x4e01a0(int * * param_1, char param_2, int * * param_3, _String_base * param_4);
undefined __thiscall meth_0x4e0380(undefined4 * param_1, int * * param_2);
undefined __thiscall meth_0x4e0470(int * param_1);
undefined __thiscall meth_0x4fde50(uint param_1);
undefined __thiscall meth_0x4fdea0(uint param_1);
undefined __thiscall meth_0x4fdf50(undefined4 * param_1, uint param_2);
VFX_Parameter * __thiscall VFX_Parameter(void);
VFX_Parameter * __thiscall ~VFX_Parameter(void);
undefined __thiscall meth_0x4ff580(int param_1, int * param_2);
undefined4 * __thiscall virt_meth_0x4ff950(byte param_1);
void * __thiscall meth_0x4ffcc0(int param_1);
undefined __thiscall meth_0x500580(int param_1, int * param_2, undefined4 param_3, int param_4);
VFX_Parameter * __thiscall VFX_Parameter(int param_1);
int __thiscall meth_0x619e6e(byte * param_1);
typedef struct {
    virt_meth_0x4ff950 * virt_meth_0x4ff950_0;
} VFX_Parameter::vftable_673a20;
