#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_Light;
VFX_Light * __thiscall ~VFX_Light(void);
VFX_Light * __thiscall VFX_Light(void);
undefined4 * __thiscall virt_meth_0x4e8140(byte param_1);
void * __thiscall meth_0x4e83b0(int param_1);
typedef struct {
    virt_meth_0x4e8140 * virt_meth_0x4e8140_0;
    virt_meth_0x4e7470 * virt_meth_0x4e7470_4;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_16;
    FUN_00404b70 * FUN_00404b70_20;
    FUN_00404b70 * FUN_00404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    FUN_004e1850 * FUN_004e1850_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    virt_meth_0x4e7950 * virt_meth_0x4e7950_40;
    virt_meth_0x4e83f0 * virt_meth_0x4e83f0_44;
    FUN_004080b0 * FUN_004080b0_48;
    virt_meth_0x4e1890 * virt_meth_0x4e1890_52;
    FUN_004e1930 * FUN_004e1930_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    FUN_004e0dc0 * FUN_004e0dc0_64;
    virt_meth_0x549020 * virt_meth_0x549020_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    FUN_00404b70 * FUN_00404b70_80;
    FUN_00404b70 * FUN_00404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    FUN_004e1b80 * FUN_004e1b80_96;
} VFX_Light::vftable_672ff4;
