#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_Sound;
undefined4 __thiscall virt_meth_0x4080b0(void);
undefined __thiscall virt_meth_0x4e0d70(undefined4 * param_1, undefined4 * param_2);
uint __thiscall virt_meth_0x4e0dc0(float param_1);
undefined __thiscall meth_0x4e1580(undefined4 param_1, undefined4 param_2, void * param_3, undefined4 param_4, int param_5, undefined4 param_6, undefined4 * param_7);
undefined __thiscall virt_meth_0x4e1850(undefined4 * param_1);
undefined __thiscall virt_meth_0x4e1930(undefined4 param_1, undefined4 param_2, void * param_3);
undefined __thiscall virt_meth_0x4e1b80(undefined4 param_1);
undefined __thiscall meth_0x4e1d00(int param_1);
undefined __thiscall meth_0x4e1d50(int param_1, undefined4 param_2);
undefined __thiscall virt_meth_0x4e2f00(void);
uint __thiscall virt_meth_0x4e2f50(float param_1);
VFX_Sound * __thiscall ~VFX_Sound(void);
VFX_Sound * __thiscall VFX_Sound(void);
undefined4 * __thiscall virt_meth_0x4e3240(byte param_1);
undefined __thiscall virt_meth_0x4e3290(void);
void * __thiscall meth_0x4e34b0(int param_1);
undefined __thiscall virt_meth_0x4e3530(int param_1);
undefined __thiscall meth_0x4e7450(int param_1, undefined4 param_2);
typedef struct {
    virt_meth_0x4e3240 * virt_meth_0x4e3240_0;
    virt_meth_0x4e2d10 * virt_meth_0x4e2d10_4;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_16;
    virt_meth_0x404b70 * virt_meth_0x404b70_20;
    virt_meth_0x404b70 * virt_meth_0x404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    virt_meth_0x4e1850 * virt_meth_0x4e1850_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    virt_meth_0x4e0d70 * virt_meth_0x4e0d70_40;
    virt_meth_0x4e3530 * virt_meth_0x4e3530_44;
    virt_meth_0x4080b0 * virt_meth_0x4080b0_48;
    virt_meth_0x4e3290 * virt_meth_0x4e3290_52;
    virt_meth_0x4e1930 * virt_meth_0x4e1930_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    virt_meth_0x4e2f50 * virt_meth_0x4e2f50_64;
    virt_meth_0x549020 * virt_meth_0x549020_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    virt_meth_0x4e2e40 * virt_meth_0x4e2e40_80;
    virt_meth_0x4e2f00 * virt_meth_0x4e2f00_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    virt_meth_0x4e1b80 * virt_meth_0x4e1b80_96;
} VFX_Sound::vftable_672dfc;
