#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_Rain;
VFX_Rain * __thiscall VFX_Rain(void);
VFX_Rain * __thiscall ~VFX_Rain(void);
void * __thiscall meth_0x4e6460(int param_1);
undefined __thiscall meth_0x4e64a0(float param_1, float param_2, float param_3, float param_4, float param_5);
undefined4 * __thiscall virt_meth_0x4e6a20(byte param_1);
undefined __thiscall meth_0x4e6b20(int param_1);
typedef struct {
    virt_meth_0x4e6a20 * virt_meth_0x4e6a20_0;
    virt_meth_0x4e5e60 * virt_meth_0x4e5e60_4;
    virt_meth_0x4e7330 * virt_meth_0x4e7330_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    FUN_005a9320 * FUN_005a9320_16;
    FUN_00404b70 * FUN_00404b70_20;
    FUN_00404b70 * FUN_00404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    FUN_004e1850 * FUN_004e1850_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    virt_meth_0x4e3f10 * virt_meth_0x4e3f10_40;
    virt_meth_0x4e6a40 * virt_meth_0x4e6a40_44;
    FUN_004080b0 * FUN_004080b0_48;
    virt_meth_0x4e1890 * virt_meth_0x4e1890_52;
    virt_meth_0x4e5ec0 * virt_meth_0x4e5ec0_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    FUN_004e0dc0 * FUN_004e0dc0_64;
    virt_meth_0x549020 * virt_meth_0x549020_68;
    FUN_00408d30 * FUN_00408d30_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    FUN_00404b70 * FUN_00404b70_80;
    FUN_00404b70 * FUN_00404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    FUN_004e1b80 * FUN_004e1b80_96;
} VFX_Rain::vftable_672f6c;
