#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_MotionBlur;
VFX_MotionBlur * __thiscall ~VFX_MotionBlur(void);
VFX_MotionBlur * __thiscall VFX_MotionBlur(void);
undefined4 * __thiscall virt_meth_0x4f68f0(byte param_1);
void * __thiscall meth_0x4f6910(int param_1);
undefined __thiscall virt_meth_0x4f6970(int param_1);
typedef struct {
    virt_meth_0x4f68f0 * virt_meth_0x4f68f0_0;
    virt_meth_0x4f6780 * virt_meth_0x4f6780_4;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_16;
    FUN_00404b70 * FUN_00404b70_20;
    FUN_00404b70 * FUN_00404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    FUN_004e1850 * FUN_004e1850_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    FUN_004e0d70 * FUN_004e0d70_40;
    virt_meth_0x4f6970 * virt_meth_0x4f6970_44;
    FUN_004080b0 * FUN_004080b0_48;
    virt_meth_0x4e1890 * virt_meth_0x4e1890_52;
    virt_meth_0x4f6800 * virt_meth_0x4f6800_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    FUN_004e0dc0 * FUN_004e0dc0_64;
    virt_meth_0x4f6880 * virt_meth_0x4f6880_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    FUN_00404b70 * FUN_00404b70_80;
    FUN_00404b70 * FUN_00404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    FUN_004e1b80 * FUN_004e1b80_96;
} VFX_MotionBlur::vftable_67380c;
