#include "VFX_Parameter.h"
#include "VFX_Parameter.h"
#include "VFX_Parameter.h"
#include "VFX_Parameter.h"
typedef struct {
    VFX_Parameter VFX_Parameter;
    dword mbr_0x34;
    dword mbr_0x38;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    dword mbr_0x54;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x64;
    dword mbr_0x68;
    VFX_Parameter VFX_Parameter;
    byte mbr_0xa0;
    undefined None;
    undefined None;
    undefined None;
    VFX_Parameter VFX_Parameter;
    byte mbr_0xd8;
    undefined None;
    undefined None;
    undefined None;
    VFX_Parameter VFX_Parameter;
    byte mbr_0x110;
} VFX_ParameterInfo;
VFX_ParameterInfo * __thiscall VFX_ParameterInfo(void);
VFX_ParameterInfo * __thiscall ~VFX_ParameterInfo(void);
undefined4 * __thiscall virt_meth_0x4fb430(byte param_1);
VFX_ParameterInfo * __thiscall VFX_ParameterInfo(int param_1);
void * __thiscall meth_0x4fdfb0(undefined param_1, undefined1 param_2);
void * __thiscall meth_0x4fdfd0(undefined param_1, undefined1 param_2);
void * __thiscall meth_0x4fdff0(undefined param_1, undefined1 param_2);
void * __thiscall meth_0x4fe010(undefined param_1);
void * __thiscall meth_0x4fe040(undefined4 * param_1);
void * __thiscall meth_0x4fe060(undefined4 * param_1);
void * __thiscall meth_0x4fe080(undefined4 * param_1);
void * __thiscall meth_0x4fe0a0(undefined4 * param_1);
void * __thiscall meth_0x4fe0c0(void * param_1);
void * __thiscall meth_0x4fe140(undefined4 * param_1);
void * __thiscall meth_0x4fe160(undefined param_1, undefined1 param_2);
void * __thiscall meth_0x4fe180(int param_1);
void * __thiscall meth_0x4fe1b0(int param_1);
undefined __thiscall meth_0x4fe280(void);
undefined __thiscall meth_0x4fe450(undefined4 param_1, uint param_2, undefined4 * param_3);
undefined __thiscall meth_0x4fe690(undefined4 param_1, uint param_2, undefined4 * param_3);
undefined __thiscall meth_0x4fe880(float * param_1);
undefined __thiscall meth_0x4feb20(undefined4 param_1, uint param_2, undefined2 * param_3);
undefined __thiscall meth_0x4feef0(undefined4 param_1, uint param_2, float * param_3);
undefined __thiscall meth_0x4ff1b0(undefined4 * param_1, undefined4 param_2, uint param_3, int param_4);
undefined __thiscall meth_0x4ff970(void);
undefined __thiscall meth_0x4ff970(void);
undefined __thiscall meth_0x4ffd10(void * param_1);
undefined __thiscall meth_0x500150(void * param_1);
undefined __thiscall meth_0x500760(void * param_1);
undefined __thiscall meth_0x500bc0(int param_1, int * param_2);
undefined __thiscall meth_0x501000(undefined4 param_1, undefined4 param_2, uint param_3, int param_4, int * param_5);
typedef struct {
    virt_meth_0x4fb430 * virt_meth_0x4fb430_0;
} VFX_ParameterInfo::vftable_673944;
