#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_ModelEffect;
VFX_ModelEffect * __thiscall ~VFX_ModelEffect(void);
VFX_ModelEffect * __thiscall VFX_ModelEffect(void);
undefined4 * __thiscall virt_meth_0x4e8c60(byte param_1);
void * __thiscall meth_0x4e8e00(int param_1);
typedef struct {
    virt_meth_0x4e8c60 * virt_meth_0x4e8c60_0;
    virt_meth_0x4e8650 * virt_meth_0x4e8650_4;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_16;
    virt_meth_0x404b70 * virt_meth_0x404b70_20;
    virt_meth_0x404b70 * virt_meth_0x404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    FUN_004e1850 * FUN_004e1850_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    FUN_004e0d70 * FUN_004e0d70_40;
    virt_meth_0x4e8e40 * virt_meth_0x4e8e40_44;
    FUN_004080b0 * FUN_004080b0_48;
    virt_meth_0x4e1890 * virt_meth_0x4e1890_52;
    virt_meth_0x4f6800 * virt_meth_0x4f6800_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    FUN_004e0dc0 * FUN_004e0dc0_64;
    virt_meth_0x4f6880 * virt_meth_0x4f6880_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    virt_meth_0x404b70 * virt_meth_0x404b70_80;
    virt_meth_0x404b70 * virt_meth_0x404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    FUN_004e1b80 * FUN_004e1b80_96;
} VFX_ModelEffect::vftable_67306c;
