typedef struct {
    VFX_FormatManager::vftable_67396c * vftptr_0x0;
    dword mbr_0x4;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x28;
} VFX_FormatManager;
VFX_FormatManager * __thiscall ~VFX_FormatManager(void);
undefined4 * __thiscall virt_meth_0x4fd660(byte param_1);
typedef struct {
    virt_meth_0x4fd660 * virt_meth_0x4fd660_0;
} VFX_FormatManager::vftable_67396c;
