typedef struct {
    VFX_VEGInstance::vftable_6696f8 * vftptr_0x0;
    dword mbr_0x4;
    byte mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0xc;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x14;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x24;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    dword mbr_0x38;
    dword mbr_0x3c;
    dword mbr_0x40;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
} VFX_VEGInstance;
undefined4 * __thiscall meth_0x48cda0(int param_1);
float10 __thiscall meth_0x48d9b0(char param_1);
undefined __thiscall meth_0x48dbe0(void);
undefined __thiscall meth_0x48dcc0(void);
undefined __thiscall meth_0x48df00(void);
undefined __thiscall meth_0x48e5f0(void);
VFX_VEGInstance * __thiscall ~VFX_VEGInstance(void);
VFX_VEGInstance * __thiscall VFX_VEGInstance(void);
int * __thiscall virt_meth_0x48ede0(byte param_1);
uint __thiscall meth_0x48ee30(uint param_1);
undefined __thiscall meth_0x48efb0(int param_1, undefined4 param_2, char param_3);
undefined __thiscall meth_0x48f080(int * param_1, undefined4 param_2, undefined4 param_3, int param_4, undefined4 param_5, undefined4 param_6);
typedef struct {
    virt_meth_0x48ede0 * virt_meth_0x48ede0_0;
} VFX_VEGInstance::vftable_6696f8;
