#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_Lightning;
undefined __thiscall virt_meth_0x4e8e60(undefined4 * param_1);
float10 __thiscall meth_0x4e8e90(int param_1, int param_2);
VFX_Lightning * __thiscall ~VFX_Lightning(void);
undefined4 * __thiscall virt_meth_0x4ea370(byte param_1);
undefined __thiscall meth_0x4ea6f0(undefined4 * param_1);
undefined __thiscall meth_0x4ebbb0(void * param_1, float param_2, float param_3, float param_4, int * param_5, float param_6, float10 * param_7, float param_8);
VFX_Lightning * __thiscall VFX_Lightning(void);
typedef struct {
    virt_meth_0x4ea370 * virt_meth_0x4ea370_0;
    virt_meth_0x4ec990 * virt_meth_0x4ec990_4;
    virt_meth_0x4eceb0 * virt_meth_0x4eceb0_8;
    virt_meth_0x591690 * virt_meth_0x591690_12;
    virt_meth_0x5a9320 * virt_meth_0x5a9320_16;
    virt_meth_0x404b70 * virt_meth_0x404b70_20;
    virt_meth_0x404b70 * virt_meth_0x404b70_24;
    virt_meth_0x549020 * virt_meth_0x549020_28;
    virt_meth_0x4e8e60 * virt_meth_0x4e8e60_32;
    virt_meth_0x4e1870 * virt_meth_0x4e1870_36;
    virt_meth_0x4e8f70 * virt_meth_0x4e8f70_40;
    virt_meth_0x4ea2e0 * virt_meth_0x4ea2e0_44;
    FUN_004080b0 * FUN_004080b0_48;
    virt_meth_0x4e8f30 * virt_meth_0x4e8f30_52;
    virt_meth_0x4e9170 * virt_meth_0x4e9170_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    FUN_004e0dc0 * FUN_004e0dc0_64;
    virt_meth_0x549020 * virt_meth_0x549020_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    virt_meth_0x404b70 * virt_meth_0x404b70_80;
    virt_meth_0x404b70 * virt_meth_0x404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    virt_meth_0x4e9530 * virt_meth_0x4e9530_96;
} VFX_Lightning::vftable_6730ec;
