#include "VFX_EffectInstance.h"
typedef struct {
    VFX_EffectInstance VFX_EffectInstance;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
} VFX_Model;
undefined __thiscall virt_meth_0x4f30c0(int * * param_1, undefined4 param_2, uint param_3, void * param_4, undefined4 * param_5, undefined4 * param_6);
undefined __thiscall meth_0x4f3a00(_String_base * param_1);
void * __thiscall meth_0x4f4000(int param_1);
VFX_Model * __thiscall ~VFX_Model(void);
undefined __thiscall meth_0x4f43e0(_String_base * param_1, float param_2);
undefined4 * __thiscall virt_meth_0x4f45c0(byte param_1);
VFX_Model * __thiscall VFX_Model(void);
undefined __thiscall meth_0x4f47b0(_String_base * param_1, float param_2);
typedef struct {
    virt_meth_0x4f45c0 * virt_meth_0x4f45c0_0;
    virt_meth_0x4f30c0 * virt_meth_0x4f30c0_4;
    virt_meth_0x4f36f0 * virt_meth_0x4f36f0_8;
    virt_meth_0x4f3720 * virt_meth_0x4f3720_12;
    virt_meth_0x4f3740 * virt_meth_0x4f3740_16;
    virt_meth_0x4f3760 * virt_meth_0x4f3760_20;
    virt_meth_0x4f3770 * virt_meth_0x4f3770_24;
    virt_meth_0x408d30 * virt_meth_0x408d30_28;
    virt_meth_0x4f3690 * virt_meth_0x4f3690_32;
    virt_meth_0x4f36c0 * virt_meth_0x4f36c0_36;
    virt_meth_0x4f3780 * virt_meth_0x4f3780_40;
    virt_meth_0x4f4960 * virt_meth_0x4f4960_44;
    virt_meth_0x4f43d0 * virt_meth_0x4f43d0_48;
    virt_meth_0x4e1890 * virt_meth_0x4e1890_52;
    virt_meth_0x4e1930 * virt_meth_0x4e1930_56;
    virt_meth_0x4e18a0 * virt_meth_0x4e18a0_60;
    virt_meth_0x4e0dc0 * virt_meth_0x4e0dc0_64;
    virt_meth_0x549020 * virt_meth_0x549020_68;
    virt_meth_0x549020 * virt_meth_0x549020_72;
    virt_meth_0x4e0e20 * virt_meth_0x4e0e20_76;
    virt_meth_0x404b70 * virt_meth_0x404b70_80;
    virt_meth_0x404b70 * virt_meth_0x404b70_84;
    virt_meth_0x4e18b0 * virt_meth_0x4e18b0_88;
    virt_meth_0x4e18c0 * virt_meth_0x4e18c0_92;
    virt_meth_0x4e1b80 * virt_meth_0x4e1b80_96;
} VFX_Model::vftable_673714;
