typedef struct {
    WorldMap::vftable_6a017c * vftptr_0x0;
    dword mbr_0x4;
    dword mbr_0x8;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x18;
    dword mbr_0x1c;
    dword mbr_0x20;
    byte mbr_0x24;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x28;
    dword mbr_0x2c;
    dword mbr_0x30;
    dword mbr_0x34;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x44;
    dword mbr_0x48;
    dword mbr_0x4c;
    dword mbr_0x50;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    undefined None;
    dword mbr_0x60;
    dword mbr_0x64;
    dword mbr_0x68;
    dword mbr_0x6c;
    dword mbr_0x70;
    dword mbr_0x74;
    dword mbr_0x78;
    dword mbr_0x7c;
} WorldMap;
undefined __thiscall meth_0x599e60(void);
WorldMap * __thiscall WorldMap(void);
undefined __thiscall meth_0x59a1e0(void);
WorldMap * __thiscall ~WorldMap(void);
undefined __thiscall virt_meth_0x59a330(void);
int * __thiscall virt_meth_0x59a3f0(byte param_1);
undefined __thiscall virt_meth_0x59a440(undefined4 * param_1);
typedef struct {
    virt_meth_0x59a3f0 * virt_meth_0x59a3f0_0;
    virt_meth_0x59a330 * virt_meth_0x59a330_4;
    virt_meth_0x59a440 * virt_meth_0x59a440_8;
} WorldMap::vftable_6a017c;
