// Copyright 2024 OpenJE

#ifndef OPENJE_RE_CPP_INCLUDE_EDIT_HPP_
#define OPENJE_RE_CPP_INCLUDE_EDIT_HPP_

#include "openje-re/c++/include/openje_types.hpp"

#include "openje-re/c++/include/Label.hpp"
#include "openje-re/c++/include/cls_0x4abc60.hpp"

namespace F3
{
    class Edit
    {
        public:
            Label label;
            byte mbr_0xe64;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0xe68;
            dword mbr_0xe6c;
            dword mbr_0xe70;
            dword mbr_0xe74;
            dword mbr_0xe78;
            dword mbr_0xe7c;
            dword mbr_0xe80;
            dword mbr_0xe84;
            dword mbr_0xe88;
            dword mbr_0xe8c;
            cls_0x4abc60 cls_0x4abc60;
            dword mbr_0xea0;
            dword mbr_0xea4;
            dword mbr_0xea8;
            dword mbr_0xeac;
            dword mbr_0xeb0;
            dword mbr_0xeb4;
            dword mbr_0xeb8;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0xed4;
            dword mbr_0xed8;
            dword mbr_0xedc;
            dword mbr_0xee0;
            dword mbr_0xee4;
            dword mbr_0xee8;
            dword mbr_0xeec;
            dword mbr_0xef0;
            dword mbr_0xef4;
            dword mbr_0xef8;
            dword mbr_0xefc;
            dword mbr_0xf00;
            dword mbr_0xf04;
            dword mbr_0xf08;
            dword mbr_0xf0c;
            dword mbr_0xf10;
            dword mbr_0xf14;
            dword mbr_0xf18;
            dword mbr_0xf1c;
            dword mbr_0xf20;
            dword mbr_0xf24;
            dword mbr_0xf28;
            dword mbr_0xf2c;
            dword mbr_0xf30;
            dword mbr_0xf34;
            byte mbr_0xf38;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0xf3c;
            dword mbr_0xf40;
            dword mbr_0xf44;
            dword mbr_0xf48;
            dword mbr_0xf4c;
            dword mbr_0xf50;
            dword mbr_0xf54;
            dword mbr_0xf58;
            dword mbr_0xf5c;
            dword mbr_0xf60;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0xf74;
            dword mbr_0xf78;
            dword mbr_0xf7c;
            dword mbr_0xf80;
            dword mbr_0xf84;
            dword mbr_0xf88;
            dword mbr_0xf8c;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0xfa8;
            dword mbr_0xfac;
            dword mbr_0xfb0;
            dword mbr_0xfb4;
            dword mbr_0xfb8;
            dword mbr_0xfbc;
            dword mbr_0xfc0;
            dword mbr_0xfc4;
            dword mbr_0xfc8;
            dword mbr_0xfcc;
            dword mbr_0xfd0;
            dword mbr_0xfd4;
            dword mbr_0xfd8;
            dword mbr_0xfdc;
            dword mbr_0xfe0;
            dword mbr_0xfe4;
            dword mbr_0xfe8;
            dword mbr_0xfec;
            dword mbr_0xff0;
            dword mbr_0xff4;
            dword mbr_0xff8;
            dword mbr_0xffc;
            dword mbr_0x1000;
            dword mbr_0x1004;
            dword mbr_0x1008;
            byte mbr_0x100c;
            undefined None;
            undefined None;
            undefined None;
            dword mbr_0x1010;
            dword mbr_0x1014;
            byte mbr_0x1018;
            byte mbr_0x1019;
            byte mbr_0x101a;
            undefined None;
            dword mbr_0x101c;
            dword mbr_0x1020;
            dword mbr_0x1024;
            dword mbr_0x1028;
            dword mbr_0x102c;
            dword mbr_0x1030;
            dword mbr_0x1034;
            byte mbr_0x1038;

        public:
            Edit();
            ~Edit();
    };
} // namespace F3

#endif // OPENJE_RE_CPP_INCLUDE_EDIT_HPP_
